[package]
name = "rec"
version = "0.1.0"
authors = ["Gabe Fierro <gtfierro225@gmail.com>"]

[dependencies]
clap = "2.31.2"
chrono = "0.4"
time = "*"

[dependencies.rusqlite]
version = "0.19.0"
features = ["bundled"]
